Vagrant::Config.run do |config|

  config.vm.box       = 'lucid32'
  config.vm.box_url   = 'http://files.vagrantup.com/lucid32.box'
  config.vm.host_name = 'base'

  config.ssh.forward_agent = true

  config.vm.forward_port 5000, 5000

  config.vm.customize [
    'modifyvm', :id,
    '--memory', '2048',
    '--cpus',   '4',
    '--ioapic', 'on',
    '--name',   'base'
  ]

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['../../site-cookbooks', '../../cookbooks']
    chef.roles_path     = '../../roles'

    chef.json = {
      :user => ENV['USER']
    }

    chef.add_role 'base'
    chef.add_role 'java'

    # You can put together a user-specific cookbook to set up your own VM how
    # you like by adding it to cookbooks/your_user_name
    chef.add_recipe ENV['USER'] if File.directory?("../../site-cookbooks/#{ENV['USER']}")
  end

end

# vim:syntax=ruby filetype=ruby
