alias ll='ls -la'
alias ..='cd ..'
alias d='ls -l | grep -E "^d"'
cd ~


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

export SRC_HOME=/home/art/src/
set -o vi
export PATH=~/bin:$PATH
alias gilg='git log --oneline -20 --graph'
alias gil='git log --oneline -20'

function git_diff() {
  git diff --no-ext-diff -w "$@" | vim -R -
}
